server {
    listen 80;
    server_name localhost;

    # Route to App 1 Container
    location /app1/ {
        proxy_pass http://app1_container:80/;
    }

    # Route to App 2 Container
    location /app2/ {
        proxy_pass http://app2_container:80/;
    }
}
